config/routes.rb
Rails.application.routes.draw do
  get '/carousel', to: 'carousel#index'

  get '/stocks/:alias', to: 'stock#show', as: 'stock_show'

  get '/stocks', to: 'stock#index', as: 'stocks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carousel_controller.rb
class CarouselController < ApplicationController
  require 'rest-client'

  def index
    url = 'localhost:1234/carousel'
    response = RestClient.get(url)
    @carousel_stocks = JSON.parse(response)
  end
end

app/controllers/stock_controller.rb
class StockController < ApplicationController
  require 'rest-client'
  def show
    stock_alias = params[:alias]
    url = "localhost:1234/stocks/#{stock_alias}"
    response = RestClient.get(url)
    @stock = JSON.parse(response)
  end

  def index
    url = 'localhost:1234/stocks'
    response = RestClient.get(url)
    @stocks = JSON.parse(response)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carousel/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Alias</th>
    <th>Value</th>
    <th>Direction</th>
    <th>Spread</th>
    <th>Link</th>
  </tr>
  <% @carousel_stocks.each do |stock| %>
    <tr>
        <td><%= stock["Name"] %></td>
        <td><%= stock["Alias"] %></td>
        <td><%= stock["Value"] %></td>
        <td><%= stock["Direction"] %></td>
        <td><%= stock["Spread"] %></td>
        <td><%= link_to "Conferir Stock", stock_show_url(stock["Alias"]) %></td>
    </tr>
  <% end %>
  </div>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stocks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stock/index.html.erb
<table id="example" class="display" style="width:100%">
<thead>
  <tr>
	  <th>Date</th>
	  <th>StockCode</th> 
	  <th>StockName</th> 
	  <th>Value</th> 
	  <th>ValueFormatted</th>
	  <th>ChangeDay</th> 
	  <th>ChangeDayFormatted</th>
	  <th>Change12M</th> 
	  <th>Change12MFormatted</th>
	  <th>Volume</th>
	  <th>VolumeFormatted</th>
    <th>Link</th>  
  </tr>
</thead>
<tbody>
  <% @stocks.each do |stock| %>
    <tr>
        <td><%= stock["Date"] %></td>
        <td><%= stock["StockCode"] %></td>
        <td><%= stock["StockName"] %></td>
        <td><%= stock["Value"] %></td>
        <td><%= stock["ValueFormatted"] %></td>
        <td><%= stock["ChangeDay"] %></td>
        <td><%= stock["ChangeDayFormatted"] %></td>
        <td><%= stock["Change12M"] %></td>
        <td><%= stock["Change12MFormatted"] %></td>
        <td><%= stock["Volume"] %></td>
        <td><%= stock["VolumeFormatted"] %></td>
      <td><%= link_to "info", stock_show_url(stock["StockCode"]) %>
    </tr>
  <% end %>
</tbody>
</table>
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
  $(document).ready(function () {
    $('#example').DataTable({
        paging: false,
        searching: false,
        info: false,
        order: [],
    });
});
</script>

app/views/stock/show.html.erb
<h1><%= "#{@stock["BovespaName"]} (#{@stock["StockCode"]})"%></h1>
<table>
  <tr>
    <th>StockId</th>
    <th>StockCode</th>
    <th>StockName</th>
    <th>StockTypeId</th>
    <th>CompanyId</th>
    <th>BovespaName</th>
    <th>SectorId</th>
    <th>SectorName</th>
    <th>LOTE</th>
    <th>DATA_BRASIL</th>
    <th>VALOR</th>
    <th>OSCILACAO</th>
    <th>ABERTURA</th>
    <th>FECHAMENT_ANT</th>
    <th>MINIMO</th>
    <th>MAXIMO</th>
    <th>MEDIA</th>
    <th>NEGOCIO</th>
    <th>QUANTIDADE</th>
    <th>VOLUME_TOTAL</th>
    <th>VARIACAO_7D</th>
    <th>VARIACAO_SEM</th>
    <th>VARIACAO_MES</th>
    <th>VARIACAO_30D</th>
    <th>VARIACAO_ANO</th>
    <th>VARIACAO_12M</th>
    <th>OFERTA_COMPRA</th>
    <th>QTD_OFERTA_COMPRA</th>
    <th>OFERTA_VENDA</th>
    <th>QTD_OFERTA_VENDA</th>
    <th>MAXIMO_52S</th>
    <th>MINIMO_52S</th>
    <th>VOLUME_MEDIO_21D</th>
    <th>PERCENT_MIN_52S</th>
    <th>PERCENT_MAX_52S</th>
    <th>BETA</th>
    <th>StandardLot</th>
    <th>MarketSegment</th>
  </tr>
  <tr>
    <td><%= @stock["StockId"] %></td>
    <td><%= @stock["StockCode"] %></td>
    <td><%= @stock["StockName"] %></td>
    <td><%= @stock["StockTypeId"] %></td>
    <td><%= @stock["CompanyId"] %></td>
    <td><%= @stock["BovespaName"] %></td>
    <td><%= @stock["SectorId"] %></td>
    <td><%= @stock["SectorName"] %></td>
    <td><%= @stock["LOTE"] %></td>
    <td><%= @stock["DATA_BRASIL"] %></td>
    <td><%= @stock["VALOR"] %></td>
    <td><%= @stock["OSCILACAO"] %></td>
    <td><%= @stock["ABERTURA"] %></td>
    <td><%= @stock["FECHAMENT_ANT"] %></td>
    <td><%= @stock["MINIMO"] %></td>
    <td><%= @stock["MAXIMO"] %></td>
    <td><%= @stock["MEDIA"] %></td>
    <td><%= @stock["NEGOCIO"] %></td>
    <td><%= @stock["QUANTIDADE"] %></td>
    <td><%= @stock["VOLUME_TOTAL"] %></td>
    <td><%= @stock["VARIACAO_7D"] %></td>
    <td><%= @stock["VARIACAO_SEM"] %></td>
    <td><%= @stock["VARIACAO_MES"] %></td>
    <td><%= @stock["VARIACAO_30D"] %></td>
    <td><%= @stock["VARIACAO_ANO"] %></td>
    <td><%= @stock["VARIACAO_12M"] %></td>
    <td><%= @stock["OFERTA_COMPRA"] %></td>
    <td><%= @stock["QTD_OFERTA_COMPRA"] %></td>
    <td><%= @stock["OFERTA_VENDA"] %></td>
    <td><%= @stock["QTD_OFERTA_VENDA"] %></td>
    <td><%= @stock["MAXIMO_52S"] %></td>
    <td><%= @stock["MINIMO_52S"] %></td>
    <td><%= @stock["VOLUME_MEDIO_21D"] %></td>
    <td><%= @stock["PERCENT_MIN_52S"] %></td>
    <td><%= @stock["PERCENT_MAX_52S"] %></td>
    <td><%= @stock["BETA"] %></td>
    <td><%= @stock["StandardLot"] %></td>
    <td><%= @stock["MarketSegment"] %></td>
  </tr>
</table>